theme: jekyll-theme-minimal

title: "Smith-Sweeney Consulting"
logo: smithsweeney-logo-v3-borderless.png
description: " "
show_downloads: false
is_user_page: false
is_project_page: false
google_analytics: [Your Google Analytics tracking ID]
